/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class RateCardItem {
	public static final String PRICEUOM_HOURLY = 'Hourly';
	public static final String PRICEUOM_DAILY = 'Daily';
	public static final String PRICEUOM_WEEKLY = 'Weekly';
	public static final String PRICEUOM_MONTHLY = 'Monthly';
	public static final String PRICEUOM_YEARLY = 'Yearly';
}
