name: Create GCE Runners

on:
  workflow_call:
    outputs:
      label1:
        description: 'The label of the 1st gce self hosted runner'
        value: ${{ jobs.create-runner1.outputs.label }}
      label2:
        description: 'The label of the 2nd gce self hosted runner'
        value: ${{ jobs.create-runner2.outputs.label }}
      label3:
        description: 'The label of the 3rd gce self hosted runner'
        value: ${{ jobs.create-runner3.outputs.label }}
      label4:
        description: 'The label of the 4th gce self hosted runner'
        value: ${{ jobs.create-runner4.outputs.label }}
      label5:
        description: 'The label of the 5th gce self hosted runner'
        value: ${{ jobs.create-runner5.outputs.label }}
jobs:
  create-runner1:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-gce-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - id: create-gce-runner
        uses: ./.github/actions/create-gce-runner
        with:
          token: ${{ secrets.GCP_GH_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  create-runner2:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-gce-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - id: create-gce-runner
        uses: ./.github/actions/create-gce-runner
        with:
          token: ${{ secrets.GCP_GH_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  create-runner3:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-gce-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - id: create-gce-runner
        uses: ./.github/actions/create-gce-runner
        with:
          token: ${{ secrets.GCP_GH_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  create-runner4:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-gce-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - id: create-gce-runner
        uses: ./.github/actions/create-gce-runner
        with:
          token: ${{ secrets.GCP_GH_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  create-runner5:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-gce-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - id: create-gce-runner
        uses: ./.github/actions/create-gce-runner
        with:
          token: ${{ secrets.GCP_GH_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
  setup-runner1:
    needs: [create-runner1]
    runs-on: ${{ needs.create-runner1.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-gce-runner
  setup-runner2:
    needs: [create-runner2]
    runs-on: ${{ needs.create-runner2.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-gce-runner
  setup-runner3:
    needs: [create-runner3]
    runs-on: ${{ needs.create-runner3.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-gce-runner
  setup-runner4:
    needs: [create-runner4]
    runs-on: ${{ needs.create-runner4.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-gce-runner
  setup-runner5:
    needs: [create-runner5]
    runs-on: ${{ needs.create-runner5.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-gce-runner
