name: Create GCE Runner
inputs:
  token:
    required: true
  project_id:
    required: true
  service_account_key:
    required: true
outputs:
  label:
    value: ${{ steps.create-runner.outputs.label }}
runs:
  using: 'composite'
  steps:
    - id: create-runner
      name: Create self hosted runner
      uses: related-sciences/gce-github-runner@main
      with:
        token: ${{ inputs.token }}
        project_id: ${{ inputs.project_id }}
        service_account_key: ${{ inputs.service_account_key }}
        image_project: ubuntu-os-cloud
        image_family: ubuntu-2004-lts
